# Version is dependent to Docker version
# YML file is indent dependent
version: "3"
# Services to run
services:
  friendservice:
    #image: friendservicevapor3_friendservice
    # This service will be build from file
    build:
      context: .
      dockerfile: Dockerfile
    ## Add custom commad to run instead of the command from Dockerfile
    command: vapor run --hostname=friendservice --port=9000
    # Just a workaround, DB is slow to start
    restart: unless-stopped
    # HOSTPORT:CONTAINERPORT
    ports:
      - "8080:9000"
    # This means that mysql container needs to be started before friendservice
    depends_on:
      - "mysql"
    environment:
      DB_HOSTNAME: "mysql"
      DB_USER: "vapor"
      DB_PASSWORD: "friend"
      DB_DATABASE: "friends"
  mysql:
    image: mysql:5.7
    # Open port to localhost if you need to access with sql app
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "vapor"
      MYSQL_PASSWORD: "friend"
      MYSQL_ROOT_PASSWORD: "default"
      MYSQL_DATABASE: friends
